# -*- coding: utf-8 -*-
"""Find the Largest Among Three Numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eSN89vtpkldk8xXZHojdOWM37Ohi6AMr
"""

First_intiger=int(input())
Second_intiger=int(input())
Third_intiger=int(input())
if First_intiger > Second_intiger and First_intiger > Third_intiger:
  print("Largest nuber is",First_intiger)
elif Second_intiger > First_intiger and Second_intiger > Third_intiger:
  print("Largest nuber is",Second_intiger)
else:
  print("Largest nuber is",Third_intiger)